services:
  pg:
    image: ghcr.io/tassa-yoniso-manasi-karoto/langkit-ichiran-pg:latest
    shm_size: "1gb"
    environment:
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${PWD}/docker/pgdata:/var/lib/postgresql/data

  main:
    image: ghcr.io/tassa-yoniso-manasi-karoto/langkit-ichiran-main:latest
